name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build RPM package 7
      id: rpm7
      uses: naveenrajm7/rpmbuild@master
      with:
        spec_file: "smartctl-exporter-el7.spec"

    - name: build RPM package 8
      id: rpm8
      uses: naveenrajm7/rpmbuild@master
      with:
        spec_file: "smartctl-exporter-el8.spec"

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Binary RPM
        path: ${{ steps.rpm.outputs.rpm_dir_path }}
